# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN npm install --production

# Bundle app source
COPY . .

# Expose no ports (uses stdio)

# Start the MCP server
CMD ["node", "index.js"]
